# Generated by Django 6.0.6 on 2026-06-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Loja')),
                ('slug', models.SlugField(help_text='Ex: acaisuperdelicia', unique=True, verbose_name='URL da Loja')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp para pedidos')),
                ('address', models.TextField(verbose_name='Endereço Completo')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Pedido Mínimo')),
                ('standard_delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taxa de Entrega')),
                ('estimated_delivery_time', models.CharField(choices=[('15-30', '15 a 30 minutos'), ('30-45', '30 a 45 minutos'), ('45-60', '45 a 60 minutos'), ('60-90', '60 a 90 minutos'), ('90+', 'Acima de 90 minutos')], default='15-30', max_length=10, verbose_name='Tempo estimado')),
                ('is_open', models.BooleanField(default=False, verbose_name='Loja Aberta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('FREE', 'Grátis (Até R$1000/mês em vendas)'), ('PLUS', 'Ilimitado'), ('PREMIUM', 'Premium + Dashboard')], default='FREE', max_length=10, verbose_name='Plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='Assinatura Ativa')),
                ('pagarme_subscription_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Pagar.me')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
    ]
