# Generated by Django 6.0.6 on 2026-06-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('max_free_limits', models.PositiveIntegerField(default=0, help_text='Quantos itens o cliente pode escolher?', verbose_name='Máximo de Itens')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.store')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Ingrediente')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor cobrado em extras adicionais', max_digits=5, verbose_name='Preço Adicional')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: 500ml, Barca 1L', max_length=50, verbose_name='Nome do Tamanho')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço Base')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='tenants.store')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanhos',
                'ordering': ['order'],
            },
        ),
    ]
